//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronMotorsService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Maintenance()
        {
            this.MaintenanceWorker = new HashSet<MaintenanceWorker>();
        }
    
        public int Id { get; set; }
        public int CarServiceId { get; set; }
        public int CarId { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Description { get; set; }
        public int StatusId { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual CarService CarService { get; set; }
        public virtual MaintenanceStatus MaintenanceStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceWorker> MaintenanceWorker { get; set; }
    }
}
