//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronMotors.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientNotification
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Message { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
