//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronMotors.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceService
    {
        public int Id { get; set; }
        public int MaintenanceId { get; set; }
        public int ServiceId { get; set; }
    
        public virtual Maintenance Maintenance { get; set; }
        public virtual Service Service { get; set; }
    }
}
